name: Antithesis

on:
  workflow_call:
    secrets:
      ANTITHESIS_KEY:
        required: true
      ANTITHESIS_HTTP_AUTH:
        required: true

  # Just for testing - remove when done.
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Zig needs LLVM 16 to build; the default Ubuntu packages are only at 14.
      - run: |
          wget https://apt.llvm.org/llvm.sh && \
          chmod +x llvm.sh && sudo ./llvm.sh 16 \
          && sudo apt-get install -y clang-16 clang-tools-16 clang-16-doc libclang-common-16-dev libclang-16-dev libclang1-16 lld-16 liblld-16-dev
      # Build Zig and apply our custom patch enabling -ftrace-pc-guard. This and
      # the above step can be removed once we upstream this.
      - run: |
          cd /tmp && \
          wget https://ziglang.org/download/0.11.0/zig-0.11.0.tar.xz && \
          tar -xf zig-0.11.0.tar.xz && cd zig-0.11.0 && \
          patch -p1 < "${GITHUB_WORKSPACE}/tools/antithesis/zig.patch" && \
          mkdir build && cd build && \
          cmake .. && make -j4
      # Fetch libvoidstar from Antithesis, and make it available in /usr/local/lib.
      - run: |
          mkdir -p tools/antithesis/lib && \
          curl -o tools/antithesis/lib/libvoidstar.so https://${{ secrets.ANTITHESIS_HTTP_AUTH }}@antithesis.com/assets/instrumentation/libvoidstar.so && \
          sudo cp tools/antithesis/lib/libvoidstar.so /usr/local/lib
      - run: /tmp/zig-0.11.0/build/stage3/bin/zig build -Dantithesis antithesis_workload antithesis_api install
      - run: ./tools/antithesis/scripts/build.sh antithesis-latest
      - run: echo "${{ secrets.ANTITHESIS_KEY }}" > /tmp/key
      - run: ./tools/antithesis/scripts/push.sh antithesis-latest
