name: "Release (validate)"

on:
  schedule:
    - cron: 0 0 0 1 1 ? 1970 # Never for now, planned to run every six hours

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
      - uses: actions/setup-go@v4
      - uses: actions/setup-java@v3
      - uses: actions/setup-node@v3

      - run: ./scripts/install_zig.sh

      - run: ./zig/zig build dotnet_client:ci -- --release-validate
      - run: ./zig/zig build go_client:ci     -- --release-validate
      - run: ./zig/zig build java_client:ci   -- --release-validate
      - run: ./zig/zig build node_client:ci   -- --release-validate

  alert_failure:
    runs-on: ubuntu-latest
    needs: [validate]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - name: Alert if anything failed
        run: |
          export URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" && \
          curl -d "text=Release validation failed! See ${URL} for more information." -d "channel=C04RWHT9EP5" -H "Authorization: Bearer ${{ secrets.SLACK_TOKEN }}" -X POST https://slack.com/api/chat.postMessage
